#!/usr/bin/python
# -*- Mode:Python; indent-tabs-mode:nil; tab-width:4 -*-

# Grab an essid and passphrase from /boot/uboot/networks.txt
# and replace current entries for wlan0 in /etc/network/interfaces

import io
import re

USER_NETWORK_CONF_FILE = "/boot/uboot/network.txt"
INTERFACES_FILE = "/etc/network/interfaces"

i = 0
with open(USER_NETWORK_CONF_FILE, "r") as fin:
     for line in fin:
          line = line.rstrip().lstrip() # remove leading and trailing whitespace
          if len(line) == 0 or line[0] == '#':
               continue
          if i == 0:
               essid = line
               i = 1
          else:
               psk = line
               break

if essid and psk:
     print("Doing it")
     intf = open(INTERFACES_FILE, "r")
     conf = intf.read()
     intf.close()
     conf = re.sub('\n[ \t]*wpa-essid[ \t]+[^\n]*\n',
            '\nwpa-essid "%s"\n' % essid,
            conf)
     conf = re.sub('\n[ \t]*wpa-psk[ \t]+[^\n]*\n',
            '\nwpa-psk "%s"\n' % psk,
            conf)
     intf = open(INTERFACES_FILE, "w")
     intf.write(conf)
     intf.close()
